package jump

import (
	"encoding/json"
	"fmt"
	"strconv"

	"gopkg.in/yaml.v3"
)

const (
	ManagedMarker = "Managed by Clash Jump Manager"
	LegacyMarker  = "Generated by Clash 跳板管理器"
)

type ServerPort struct {
	Server string `json:"server" yaml:"server"`
	Port   int    `json:"port" yaml:"port"`
}

type MatchRule struct {
	Mode        string       `json:"mode" yaml:"mode"`
	Servers     []string     `json:"servers" yaml:"servers"`
	ServerPorts []ServerPort `json:"server_ports" yaml:"server_ports"`
	NodeNames   []string     `json:"node_names" yaml:"node_names"`
}

type JumpNode struct {
	Name              string         `json:"name" yaml:"name"`
	Type              string         `json:"type" yaml:"type"`
	Server            string         `json:"server" yaml:"server"`
	Port              Port           `json:"port" yaml:"port"`
	Password          string         `json:"password" yaml:"password"`
	UUID              string         `json:"uuid" yaml:"uuid"`
	SNI               string         `json:"sni" yaml:"sni"`
	SkipCertVerify    bool           `json:"skip_cert_verify" yaml:"skip-cert-verify"`
	Up                string         `json:"up" yaml:"up"`
	Down              string         `json:"down" yaml:"down"`
	Cipher            string         `json:"cipher" yaml:"cipher"`
	AlterID           int            `json:"alterId" yaml:"alterId"`
	UDP               bool           `json:"udp" yaml:"udp"`
	Network           string         `json:"network" yaml:"network"`
	WSOpts            map[string]any `json:"ws_opts,omitempty" yaml:"ws-opts"`
	TLS               bool           `json:"tls" yaml:"tls"`
	ClientFingerprint string         `json:"client_fingerprint" yaml:"client-fingerprint"`
	ALPN              []string       `json:"alpn,omitempty" yaml:"alpn"`
	Flow              string         `json:"flow" yaml:"flow"`
	ServerName        string         `json:"servername" yaml:"servername"`
	RealityOpts       map[string]any `json:"reality_opts,omitempty" yaml:"reality-opts"`
	Plugin            string         `json:"plugin" yaml:"plugin"`
	PluginOpts        map[string]any `json:"plugin_opts,omitempty" yaml:"plugin-opts"`
}

type JumpSource struct {
	SubUID string   `json:"sub_uid"`
	Node   JumpNode `json:"node"`
}

type State struct {
	Enabled     bool                 `json:"enabled"`
	Source      *JumpSource          `json:"source"`
	Targets     []string             `json:"targets"`
	TargetRules map[string]MatchRule `json:"target_rules"`
}

func NormalizeState(state *State, defaultRule func(uid string) MatchRule) {
	if state.TargetRules == nil {
		state.TargetRules = map[string]MatchRule{}
	}
	seen := map[string]bool{}
	targets := make([]string, 0, len(state.Targets))
	for _, uid := range state.Targets {
		if uid == "" || seen[uid] {
			continue
		}
		seen[uid] = true
		targets = append(targets, uid)
	}
	state.Targets = targets
	for uid := range state.TargetRules {
		if !seen[uid] {
			delete(state.TargetRules, uid)
		}
	}
	for _, uid := range state.Targets {
		if _, ok := state.TargetRules[uid]; !ok && defaultRule != nil {
			state.TargetRules[uid] = defaultRule(uid)
		}
	}
}

func RedactNode(node JumpNode, mask bool) JumpNode {
	replacement := ""
	if mask {
		replacement = "***"
	}
	if node.Password != "" {
		node.Password = replacement
	}
	if node.UUID != "" {
		node.UUID = replacement
	}
	if node.WSOpts != nil {
		if mask {
			node.WSOpts = map[string]any{"redacted": replacement}
		} else {
			node.WSOpts = nil
		}
	}
	if node.RealityOpts != nil {
		if mask {
			node.RealityOpts = map[string]any{"redacted": replacement}
		} else {
			node.RealityOpts = nil
		}
	}
	if node.PluginOpts != nil {
		if mask {
			node.PluginOpts = map[string]any{"redacted": replacement}
		} else {
			node.PluginOpts = nil
		}
	}
	return node
}

func PublicState(state State) State {
	if state.TargetRules == nil {
		state.TargetRules = map[string]MatchRule{}
	}
	if state.Source != nil {
		source := *state.Source
		source.Node = RedactNode(source.Node, false)
		state.Source = &source
	}
	return state
}

func JSString(value any) (string, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return string(raw), nil
}

type Port int

func (p *Port) UnmarshalYAML(value *yaml.Node) error {
	switch value.Kind {
	case yaml.ScalarNode:
		if value.Value == "" {
			*p = 0
			return nil
		}
		port, err := strconv.Atoi(value.Value)
		if err == nil {
			*p = Port(port)
			return nil
		}
		var asFloat float64
		if floatErr := value.Decode(&asFloat); floatErr == nil {
			*p = Port(asFloat)
			return nil
		}
		return fmt.Errorf("invalid port %q", value.Value)
	default:
		var port int
		if err := value.Decode(&port); err != nil {
			return err
		}
		*p = Port(port)
		return nil
	}
}
