package store_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"clash-jump-manager/internal/clash"
	"clash-jump-manager/internal/jump"
	"clash-jump-manager/internal/store"
)

func TestSaveStateRedactsJumpNodeSecrets(t *testing.T) {
	path := filepath.Join(t.TempDir(), "state.json")
	state := jump.State{
		Enabled: true,
		Source: &jump.JumpSource{
			SubUID: "remote1",
			Node: jump.JumpNode{
				Name:     "jump",
				Type:     "hysteria2",
				Server:   "jump.example.com",
				Port:     443,
				Password: "secret-password",
				UUID:     "secret-uuid",
				SNI:      "jump.example.com",
			},
		},
		Targets: []string{"remote2"},
	}

	if err := store.SaveState(path, state); err != nil {
		t.Fatalf("SaveState returned error: %v", err)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read state: %v", err)
	}
	if strings.Contains(string(raw), "secret-password") || strings.Contains(string(raw), "secret-uuid") {
		t.Fatalf("state file leaked secrets:\n%s", raw)
	}

	var saved jump.State
	if err := json.Unmarshal(raw, &saved); err != nil {
		t.Fatalf("unmarshal saved state: %v", err)
	}
	if saved.Source == nil || saved.Source.Node.Password != "" || saved.Source.Node.UUID != "" {
		t.Fatalf("expected saved source node secrets to be blank, got %#v", saved.Source)
	}
}

func TestResetManagedScriptsOnlyClearsManagedScriptsAndBacksUp(t *testing.T) {
	root := t.TempDir()
	profilesDir := filepath.Join(root, "profiles")
	backupDir := filepath.Join(root, "backups")
	if err := os.MkdirAll(profilesDir, 0o755); err != nil {
		t.Fatalf("mkdir profiles: %v", err)
	}
	customPath := filepath.Join(profilesDir, "customScript.js")
	managedPath := filepath.Join(profilesDir, "managedScript.js")
	customScript := "// user custom script\nfunction main(config) { config.mode = 'global'; return config; }\n"
	managedScript := "// Generated by Clash 跳板管理器\nfunction main(config) { config.mode = 'rule'; return config; }\n"
	if err := os.WriteFile(customPath, []byte(customScript), 0o644); err != nil {
		t.Fatalf("write custom script: %v", err)
	}
	if err := os.WriteFile(managedPath, []byte(managedScript), 0o644); err != nil {
		t.Fatalf("write managed script: %v", err)
	}

	actions, err := store.ResetManagedScripts([]clash.ProfileItem{
		{Type: "script", UID: "customScript"},
		{Type: "script", UID: "managedScript"},
	}, profilesDir, backupDir)
	if err != nil {
		t.Fatalf("ResetManagedScripts returned error: %v", err)
	}

	customAfter, err := os.ReadFile(customPath)
	if err != nil {
		t.Fatalf("read custom script: %v", err)
	}
	if string(customAfter) != customScript {
		t.Fatalf("custom script was modified:\n%s", customAfter)
	}
	managedAfter, err := os.ReadFile(managedPath)
	if err != nil {
		t.Fatalf("read managed script: %v", err)
	}
	if !strings.Contains(string(managedAfter), jump.ManagedMarker) || !strings.Contains(string(managedAfter), "No active jump proxy rules") {
		t.Fatalf("managed script was not replaced with noop script:\n%s", managedAfter)
	}
	if len(actions) != 1 || actions[0].ScriptUID != "managedScript" || actions[0].BackupPath == "" {
		t.Fatalf("unexpected reset actions: %#v", actions)
	}
	backup, err := os.ReadFile(actions[0].BackupPath)
	if err != nil {
		t.Fatalf("read backup: %v", err)
	}
	if string(backup) != managedScript {
		t.Fatalf("backup did not preserve original managed script:\n%s", backup)
	}
}

func TestDisableForeignJumpScriptRequiresForeignDialerProxyAndBacksUp(t *testing.T) {
	root := t.TempDir()
	profilesDir := filepath.Join(root, "profiles")
	backupDir := filepath.Join(root, "backups")
	if err := os.MkdirAll(profilesDir, 0o755); err != nil {
		t.Fatalf("mkdir profiles: %v", err)
	}
	foreignPath := filepath.Join(profilesDir, "foreignScript.js")
	normalPath := filepath.Join(profilesDir, "normalScript.js")
	foreignScript := "function main(config) { config.proxies.forEach(p => p['dialer-proxy'] = 'old-jump'); return config; }\n"
	normalScript := "function main(config) { config.mode = 'rule'; return config; }\n"
	if err := os.WriteFile(foreignPath, []byte(foreignScript), 0o644); err != nil {
		t.Fatalf("write foreign script: %v", err)
	}
	if err := os.WriteFile(normalPath, []byte(normalScript), 0o644); err != nil {
		t.Fatalf("write normal script: %v", err)
	}

	if _, err := store.DisableForeignJumpScript(normalPath, backupDir); err == nil {
		t.Fatal("expected normal script disable to be rejected")
	}

	action, err := store.DisableForeignJumpScript(foreignPath, backupDir)
	if err != nil {
		t.Fatalf("DisableForeignJumpScript returned error: %v", err)
	}
	if action.Action != "disabled_foreign_jump" || action.ScriptUID != "foreignScript" || action.BackupPath == "" {
		t.Fatalf("unexpected action: %#v", action)
	}
	after, err := os.ReadFile(foreignPath)
	if err != nil {
		t.Fatalf("read disabled script: %v", err)
	}
	if strings.Contains(string(after), "dialer-proxy") || !strings.Contains(string(after), "return config") {
		t.Fatalf("expected foreign jump to be replaced by noop script:\n%s", after)
	}
	backup, err := os.ReadFile(action.BackupPath)
	if err != nil {
		t.Fatalf("read backup: %v", err)
	}
	if string(backup) != foreignScript {
		t.Fatalf("backup did not preserve original foreign script:\n%s", backup)
	}
}
